# Generated by Django 4.2.10 on 2024-03-11 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_comment_comment_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
